### ISSUE TITLE
About Excel File Size

### ISSUE THREAD

**Issue by kelbindev** [RomanPavelko/SwiftExcel#11]
Hi,
Your library is amazing and easy to use
This thread isnt about issue about your libraly, 
but i do want to check with anyone here see if anyone has any idea what's happening

so i encounter below issue

1. the file generated by the library is 129MB, but after i open and save the file directly without any changes, it will become 146mb, and im also not sure why when the file initially saves, the date is 2019
can refer to the screenshot below for the file size
<img width="719" alt="image" src="https://user-images.githubusercontent.com/93187893/201034815-e9d9c658-1795-4e28-8a2d-36f238aa4ffb.png">
<img width="728" alt="image" src="https://user-images.githubusercontent.com/93187893/201035147-2651878d-0a9f-486e-a595-a97dc5d66384.png">

2. one of the users that need the generated file, they are using excel power query to read from the excel file, but when the file is just newly generated, when excel power query is trying to read the file, it will prompt below error,
<img width="335" alt="image" src="https://user-images.githubusercontent.com/93187893/201034243-448365de-e824-46f3-aad8-995f329a8b06.png">
but when the file is open or the file is re-saved
then this error wont prompt

anyone have any idea whats happening?
any help will be appreciated

**Comment by RomanPavelko** [comment]
Hi @kelbindev,

Thank you for pointing out the date issue. Bug has been found and fixed, see the most recent version of the library.

Regarding the file size, when you save it using Microsoft Excel the internal logic of the app is triggered and the file is being rebuilt from scratch by the program itself due to its standards and version. Perhaps because of not the most efficient methods of data structuring or some extra information that is being copied within Microsoft Excel the file becomes bigger.

And regarding the reading issue. First I'd try to generate a file using SwiftExcel with little to no data and try to read it like that, verifying if this is a library or actual data problem. If that's the library problem (no data and error still exists), please send me both files, before resaving which errors out and after resaving that passes through and I'll try to decompile them and at least try to find the issue.
