### ISSUE TITLE
Xlsx file with line breaks in cells causes Excel error

### ISSUE THREAD

**Issue by giswiz** [RomanPavelko/SwiftExcel#12]
I have created an XLSX file that contains text cells with line breaks. However, if I open that file with Excel, I get the message "We found a problem with some content in ... Do you want us to try to recover as much as we can? If you trust the source of this workbook, click "Yes"".
I am attaching a file below.
[TimingResultsV3.xlsx](https://github.com/RomanPavelko/SwiftExcel/files/10083865/TimingResultsV3.xlsx)

I'm using Microsoft Office Professional Plus 2019

**Comment by RomanPavelko** [comment]
@giswiz thanks for submitting this issue and for attaching the file, that helped a lot! The issue was in sheet name, apparently Excel doesn't allow more than 31 characters for it, yours was way longer. I added a code change that applies validation to the sheet name length and trims it if needed. Please download the latest version 1.0.14 and give it a try. Let me know if it helped.

**Comment by giswiz** [comment]
@RomanPavelko that was quick! Yes, the issue is gone with the new version, works like a charm. Thank you for the really quick response.
