### ISSUE TITLE
Is it possible generate xls file without write it to disk?

### ISSUE THREAD

**Issue by paulofloresjunior** [RomanPavelko/SwiftExcel#14]
Hi, I just start today to use your code. 
I using to generate xls report file to serve by rest API, but I don't need to keep the file in server, so to improve the API performance I want to skip the process to write to disk and read it to serve through API call. I wondering if is it possible to create the file as memorystream.

Any thoughts?

**Comment by RomanPavelko** [comment]
Hi, Paulo.

1. You do need a physical location to generate an Excel file using SwiftExcel, unfortunately you cannot do that just in memory. If SwiftExcel generated those files in-memory it would loose all performance benefits over other libraries as in-memory generation is very inefficient when scaling.
2. In a situation like yours I always recommend to return a filestream of generated file with DeleteOnClose flag.

Here is an example:
```
public ActionResult GetTemporaryFile()
{
    return File(
        new FileStream(
            your_file_path, 
            FileMode.Open, 
            FileAccess.Read, 
            FileShare.None, 
            4096, 
            FileOptions.DeleteOnClose), 
        "application/octet-stream", 
        your_file_name);
}
```

In this example I'm using FileOptions.DeleteOnClose which will delete the file as soon as stream is closed (everything is delivered to the client) so you don't need to worry about space management,

**Comment by paulofloresjunior** [comment]
Hi Roman,

Thanks for DeleteOnClose tip, save me time here.

Our server already uses SSD storage so the file writing time will not be a problem.

For me, the version 1.1.2 some times generate corrupted xlsx file, so I'm using the version 1.0.14, I can not reproduce the problem using fake data so I can't report to you simple way to reproduce the problem.

thanks again

**Comment by paulofloresjunior** [comment]
Hi there,

With this config the file generated is fine.
See here the results with and without this settings: https://tmpfiles.org/1696928/archive.zip

**Comment by paulofloresjunior** [comment]
With fake data in the "CompradorName" column, the problem does not occur. Therefore, the problem is likely to be in one of the cells in this column.

**Comment by RomanPavelko** [comment]
@paulofloresjunior thanks a lot for providing these details. Indeed the problem was in very specific forbidden XML characters. For additional performance benefits I moved enhanced XML escaping under a flag I mentioned before and turned it off by default so people could turn it on if needed. I thought the scenario with those character is quite rare but apparently it doesn't seem like it. I uploaded a new version 1.1.3 to Nuget with this flag enabled by default so you should be fine now. Even with this flag enabled the performance of version 1.1.x is still **2 times** faster than 1.0.x so I would encourage you to switch to the most recent version.

Thanks again for looking into it. Please try the new version and let me know if it works for you.

**Comment by paulofloresjunior** [comment]
This new versions seems to work fine, I will do more tests in the next days. I think you can close this issue.

Thanks again and great work with this library!
