### ISSUE TITLE
Multi-Line Values not shown correctly

### ISSUE THREAD

**Issue by miasbeck** [RomanPavelko/SwiftExcel#6]
When putting a value with a line break (CR/LF) into a cell like this:

```
using (var ew = new ExcelWriter(@"D:\Temp\Test.xlsx"))
{
    ew.Write("foo1\r\nbar1", 1, 1);
}
```

the result in Excel shows "foo1bar1" (i.e. a single line).

Entering the same value in Excel (using the Alt+Enter Key), the cell correctly contains two lines.

**Comment by RomanPavelko** [comment]
@miasbeck fixed by adding new property to `Sheet` configuration called `WrapText`. Setting it to `true` will resolve the issue. Please download the latest verision.

Here is a code example:

    var sheet = new Sheet { WrapText = true };
    using (var ew = new ExcelWriter(@"D:\Temp\Test.xlsx", sheet))
    {
        ew.Write("foo1\nbar1", 1, 1);
    }
    
Also use just `\n` for a new line like it is shown in the code example.
Thank you for bringing out this issue!

**Comment by miasbeck** [comment]
It works like a charm. Thanks so much for the swift reaction!
